### ISSUE TITLE
Hard to reproduce the evaluation result

### ISSUE THREAD

**Issue by chz816** [google-research/pegasus#108]
Hi,

I am trying to reproduce the results for PEGASUS. I generate the result using HuggingFace pipeline by the following code:
```
export DATA_DIR=./data/cnndm
SUFFIX=pegasus
OUTPUT_FILE=./output/cnndm/output-$SUFFIX.txt
python run_eval.py google/pegasus-cnn_dailymail $DATA_DIR/test.source $OUTPUT_FILE \
    --reference_path $DATA_DIR/test.target \
    --task summarization \
    --device cuda \
    --fp16 \
    --bs 16 \
```

Then I use the commonly used ```pyrouge``` package to report the performance:
```
1 ROUGE-1 Average_R: 0.35488 (95%-conf.int. 0.35268 - 0.35723)
1 ROUGE-1 Average_P: 0.39976 (95%-conf.int. 0.39701 - 0.40253)
1 ROUGE-1 Average_F: 0.36341 (95%-conf.int. 0.36131 - 0.36558)
---------------------------------------------
1 ROUGE-2 Average_R: 0.15035 (95%-conf.int. 0.14833 - 0.15247)
1 ROUGE-2 Average_P: 0.17054 (95%-conf.int. 0.16811 - 0.17293)
1 ROUGE-2 Average_F: 0.15439 (95%-conf.int. 0.15240 - 0.15641)
---------------------------------------------
1 ROUGE-L Average_R: 0.28424 (95%-conf.int. 0.28220 - 0.28657)
1 ROUGE-L Average_P: 0.31987 (95%-conf.int. 0.31731 - 0.32246)
1 ROUGE-L Average_F: 0.29088 (95%-conf.int. 0.28885 - 0.29297)
```

This performance is much lower than the reported performance on CNN/DM dataset. I check your code and I found you guys use ```rouge_score``` to calculate the ROUGE score. These unofficial ROUGE package may lead to biased result sometimes. Do you guys have any idea that why the gap between my result and reported performance is huge?

Thank you!

**Comment by JingqingZ** [comment]
Hi, the `rouge_score` maintained by Google has been tested to replicate results from the original ROUGE perl package ([reference](https://github.com/google-research/google-research/tree/master/rouge)). 

Based on the script you have provided above, I am not quite sure the exact setting you have used to load model checkpoints and decode. Some ideas (1) beam size and beam alpha can affect ROUGE score, please refer to our paper appendix to find the exact setting we used for CNNDM; (2) we didn't use fp16.

Since you're using the distribution maintained by Huggingface, please be advised to contact Huggingface if the problem persists.
